spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
logging:
  level:
    com:
      sourcery:
        pablomed:
          repository: TRACE
    org:
      springframework: TRACE
  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri: https://dev-agnxwxcor6pa7i6f.us.auth0.com/

